### ISSUE TITLE
problem with the Ã letter used in portuguese language!

### ISSUE THREAD

**Issue by georgebueno** [TimTree/wheel-of-fortune-ppt#6]
Hi Tim, great job, but I'm having this little trouble with words which have the ~ sign over it, in portuguese we need to use Ã and Õ in certain cases like the word MÃO, meaning HAND. The following other signs: Á, Ê and Ç are working fine. 
The problem is: letters with sign ~ over it are not hidden at the beginning of the game. Thanks

**Comment by TimTree** [comment]
Good catch! The letters Ã and Õ are part of the extended ASCII table, so this issue should be fixable on my end.

I will attempt to fix this for the next update.

**Comment by TimTree** [comment]
Fixed in v6.2.1 and v6.3
